
Naming/MethodName:
  Exclude:
    - 'app/models/concerns/orchestration/*/compute.rb'

Layout/LineLength:
  Max: 199

Style/FormatStringToken:
  Exclude:
    - 'app/models/concerns/orchestration/tofu/compute.rb'
